- name: copy static files
  copy:
      src: "{{role_path}}/files/"
      dest: "{{ targetDir }}"
- name: create package.json
  template:
    src: package.json.j2
    dest: "{{ targetDir }}/package.json"
- name: create mongo initialization script
  template: 
    src: mongo-init.js.j2
    dest: "{{ targetDir }}/mongo-init.js"
- name: create app entry point
  template:
    src: index.mjs.j2
    dest: "{{ targetDir }}/index.mjs"
- name: create app config
  template:
    src: config.mjs.j2
    dest: "{{ targetDir }}/config.mjs"
- name: create passport config
  when: hasSecurity
  template:
    src: passport.mjs.j2
    dest: "{{ targetDir }}/passport.mjs"
- name: create login endpoint
  when: hasSecurity
  template:
    src: auth.mjs.j2
    dest: "{{ targetDir }}/auth.mjs"
- name: create directory structure for each entity
  loop: "{{ entities }}"
  file: 
    path: "{{ targetDir }}/rest/{{ item.name|lower }}"
    state: directory
- name: create mongoose model for each entity
  loop: "{{ entities }}"
  vars:
    entity: "{{ item }}"
    fields: "{{ (entity.relations|selectattr('name','equalto','fields')|first).children|list }}"
  template: 
    src: "model.mjs.j2"
    dest: "{{ targetDir }}/rest/{{ entity.name|lower }}/{{ entity.name|lower }}.model.mjs"
- name: create rest controller for each entity
  loop: "{{ entities }}"
  vars:
    entity: "{{ item }}"
  template: 
    src: "controller.mjs.j2"
    dest: "{{ targetDir }}/rest/{{ entity.name|lower }}/{{ entity.name|lower }}.controller.mjs"
- name: create express route for each entity
  loop: "{{ entities }}"
  vars:
    entity: "{{ item }}"
  template: 
    src: "route.mjs.j2"
    dest: "{{ targetDir }}/rest/{{ entity.name|lower }}/{{ entity.name|lower }}.route.mjs"